platform :ios, '9.0'


flutter_application_path = '/Users/gaodeying/Desktop/Git_FlutterHybrid/flutter_to_native/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'iOSWithFlutterSingleVC' do

   install_all_flutter_pods(flutter_application_path)
   
   pod 'AFNetworking'
    
end

