platform :ios, '9.0'


flutter_application_path = '/Users/gaodeying/Desktop/Git_FlutterHybrid/Release/flutter_to_native_realse/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'iOSWithFlutterModuleRealse' do

   install_all_flutter_pods(flutter_application_path)
   
end
